import numpy as np
A = np.array([[1, 2, 1],[2, 2, 3]])
B = np.array([3, 4, 5])
print("A =")
print(A)
print("\nB =")
print(B)
print("\nAddition A + B =")
print(np.add(A, B))
print("\nSubtraction B - A =")
print(np.subtract(B, A))
print("\nMultiplication A * B =")
print(np.multiply(A, B))
print("\nDivision A / B =")
print(np.divide(A, B))
print("\nPower A^2 =")
print(np.power(A, 2))
print("\nPower A^B =")
print(np.power(A, B))
